version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local

# networks:
#   my_custom_network:
#     external: true
